### ISSUE TITLE
Update comment or change flag name

### ISSUE THREAD

**Issue by istarkov** [jlongster/redux-simple-router#10]
[Here](https://github.com/jlongster/redux-simple-router/blob/master/src/index.js#L54) in comment you use 
`avoidRouterUpdate` but in code it has a name `noRouterUpdate`.

To keep it in sync it's needed to update flag name or comment.

PS:
For me `avoidRouterUpdate` looks better than `noRouterUpdate`

**Comment by jlongster** [comment]
@istarkov Thanks for pointing that out!

I changed it because `avoidRouterUpdate` sounded too much like something that was only applied for that action. But in reality, it changes a flag in the app state permanently, so all future path changes don't trigger a router change until you pass `true`. This is fine because it's usually used when you want to switch into a "replay" mode or something like that. It's hard to do ephemeral state with redux.

**Comment by jlongster** [comment]
Done!
