### ISSUE TITLE
Cannot setup router

### ISSUE THREAD

**Issue by isikfsc** [jlongster/redux-simple-router#121]
I have the my version of example in the readme to give it a try but I cannot manage; [gist](https://gist.github.com/isikfsc/fcc5c27c22211e39ff0a).

I use node requires and es2015 sometimes so I transform with:
`browserify -t [ babelify --presets [ react es2015 ] ] main.js -o bundle.js`
also tried with `--plugins babel-plugin-transform-object-assign`.

In Safari I get the following error: 
`TypeError: undefined is not a function (evaluating 'Object.assign({}, reducer1, {
	routing: routeReducer
})')`
I think it is due to the usage of `Object.assign()`;

In Chrome:
`bundle.js:40549 Unexpected key "number" found in initialState argument passed to createStore. Expected to find one of the known reducer keys instead: "routing". Unexpected keys will be ignored.`
`Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///Users/isik/Dev/atelye/ibdb-browser/index.html' cannot be created in a document with origin 'null'.`
and I do not know why.

What is the problem here?

**Comment by kjbekkelund** [comment]
Lots of different things here. The first is that you need to set up browserify or webpack correctly, but if you just want to get it running you can e.g. use https://www.npmjs.com/package/object-assign instead of `Object.assign` directly.

The reason for `Unexpected key "number"` is that you're using `createStore` wrong. If you don't give it the initial state it might work.

The third is that you need to run a webserver to get `History` to work when using the html5 history api.

But none of these are bugs with redux-simple-router, so if you have any more questions I suggest asking them on StackOverflow.
