### ISSUE TITLE
Examples of how to use react-router API directly

### ISSUE THREAD

**Issue by Dattaya** [jlongster/redux-simple-router#5]
In the README you wrote `We encourage direct access of react-router APIs.`
Could you please give some examples of how to do it? For example, right now I have this simple fetch function as an onEnter hook:

```javascript
const fetchData = (nextState) => {
  if (nextState.location.action !== 'POP') {
    const params = nextState.params;
    const components = nextState.routes.map(route => route.component);
    fetchComponentData(store.dispatch, components, params);
  }
};
```

Is it possible to make it a redux middleware? How would I access nextState (in particular I need a component associated with the next route and params object) and other arguments in case I want to build a blocking UI.

```javascript
const { UPDATE_PATH } = require('redux-simple-router');

export default store => next => action => {
  const { type, ...rest } = action;

  if (type === UPDATE_PATH) {
    //perform a fetch
  }

  next(action);
};
```

**Comment by IwanKaramazow** [comment]
This is pure guessing & probably extremely naive, but...

```
import store from './store' 

const fetchData = nextState => {
    store.dispatch(actionCreator(nextState));
}
```

The actionCreator returns an action which encapsulates nextState & a type your redux middleware should handle.

**Comment by jlongster** [comment]
Think about it this way: how would you do it without redux-simple-rotuer? The only thing this project is for is to make sure the URL it kept up-to-date in the state.

You would do it however you normally would without this project. FWIW, I don't think that belongs in a middleware. Like you said, you need a component. You should make a higher-order component if you want to have automatic data fetching, something like this:

```js
function fetchOnEnter(Route) {
  return props => {
    return <Route onEnter=fetchData ...props>;
  }
}

const Route = fetchOnEnter(require('react-router').Route);

// ... define routes ...
```

I've been traveling all day so there is most likely a bug in the above code, but you get the idea.

**Comment by Dattaya** [comment]
@IwanKaramazow, @jlongster thank you for your answers.
> FWIW, I don't think that belongs in a middleware. 

If I'm not mistaken `react-redux-universal-hot-example` uses a middleware: [erikras/react-redux-universal-hot-example/src/redux/middleware/transitionMiddleware.js](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/redux/middleware/transitionMiddleware.js) and I like the idea, because onEnter hook has some limitations.
So I'm closing this issue since as you explained, it's not supposed to be implemented this way with `redux-simple-router`.

**Comment by jlongster** [comment]
@Dattaya what are the limitations? I'm curious because I haven't actually heard any good reason to force everything through the middleware like redux-router does.

You mentioned a "blocking UI" but you really shouldn't do that. Your new route should always render, even if the data isn't available yet, so it can show loading screens and things like that.

**Comment by IwanKaramazow** [comment]
I'm curious too. Personally the only thing I experienced with the onEnter hook & redux-simple-router was some strange behavior when writing code like this:

```javascript

function requireLogin(nextState, replaceState) {
  const { auth } = store.getState();

  if (!auth.get('hasLoaded')) {
    store.dispatch(load());
  } else if (!auth.get('user') && auth.get('hasLoaded')) {
    store.dispatch(updatePath('/login'));
}

<Route path='/login' component={Login} />
<Route path='/dashboard' component={dashboard} onEnter={requireLogin} />
```

The url changed to /login, but the dashboard component rendered instead of rendering Login...
Any 'limitation' I experienced was completely in my trying to defy the laws of async Javascript.

**Comment by Dattaya** [comment]
@jlongster maybe it's not a limitation but the lack of understanding of react-router on my side. When you transition from one subroute to another, parent's onEnter hook won't be called. In case I don't want to add this onEnter hook to every route by hand, the only way to do it is somehow dynamically by iterating over all routes? 
Before integrating `redux-router`, `react-redux-universal-hot-example` had [univerasalRouter](https://github.com/erikras/react-redux-universal-hot-example/blob/7b7608ee6c3ccfdaa34f3f0326ff78a5e3f542ef/src/helpers/universalRouter.js) and made `fetchDataForContainers` there. I just like the simplicity of the current `transitionMiddleware`.

**Comment by jlongster** [comment]
@Dattaya it's very easy to automatically add the `onEnter` hook that you need. Just create a higher-order `Route` component that does it!

I would rather figure out patterns to solve with react-router directly. But this is why it's fine to have 2 projects, and people can choose which one they want.

**Comment by Dattaya** [comment]
Thank you, @jlongster, I guess higher-order `Route` is as simple as `transitionMiddleware` both in implementation and conceptually.

**Comment by Dattaya** [comment]
@jlongster, I still need a working example for the situation when I use jsx to define routes, because the one you provided didn't work; e.g.:

```javascript
function fetchOnEnter(Route) {
  //???
}

const Route = fetchOnEnter(require('react-router').Route);

  return (
    <Route name="app" component={App} path="/">
      <IndexRoute component={Home} />
      <Route onEnter={requireLogin}>
        <Route path="about" component={About} />
      </Route>
    </Route>
  );
```
I wanted to do it somehow like so:
```javascript
  const fetchOnEnter = (Component) => {
    return class extends Component {
      ...
```
but no working solution as of yet.
Can you give any advice?

**Comment by jlongster** [comment]
Reopening this, I will respond more thoroughly will example soon :)

**Comment by jlongster** [comment]
@Dattaya so I tried doing this as well, and it does feel a little bulky. I talked with the react-router folks, and turns out there's a much more elegant way to do this.

You can pass a `createElement` option into the `Router` component, and it will be called when it needs to create a user component. This allows us to do something simple like this: https://gist.github.com/jlongster/f1d59510c8dfd3c8493a

If my component defines a static `populateStore` method, it will be called whenever the element is created. This method can populate the store, here's an example of my "index" page which fetches the latest 5 posts:

```js
    populateStore: ({ dispatch, state }, { params }) => {
      params = Object.assign({
        limit: 5
      }, params);

      return dispatch(actions.queryPosts({
        name: 'index',
        select: ['title', 'date', 'shorturl', 'abstract'],
        limit: params.limit
      }));
    },
```

This is what react-router encourages. It gets more difficult if you have async routes, but react-router is working on ways to make that work too.

**Comment by Dattaya** [comment]
Nice! `createElement` is probably good enough for me. But if someone wants a blocking UI (I think I saw folks used a tiny delay for animation, maybe there are some other use cases for it) or asynchronous routes, we don't have an elegant solution?

**Comment by IwanKaramazow** [comment]
React Router supports asynchronous routes?
If you want to go the blocking UI way, why not: (example)
```javascript
// If a callback is listed as a 3rd argument, this hook will run asynchronously,
// and the transition will block until the callback (here loadRouteAsync) is called.
function requireLogin(nextState, replaceState, loadRouteAsync) {
  function checkAuth() {
    if (!loggedIn(store.getState())) replaceState(null, '/login');
    loadRouteAsync();
  }

  if (!isAuthLoaded(store.getState())) {
    go(function*() {
      yield store.dispatch(load());
      checkAuth();
    });
  } else {
    checkAuth();
  }
}

<Route path="dashboard" onEnter={requireLogin} />
```
The UI blocks until there's been a take on the channel  ```store.dispatch(load()))``` returns. No idea if this is the most elegant way but it does the job for minimalistic authentication requirements.

**Comment by jlongster** [comment]
@IwanKaramazow's solution is good, I think that's the point of the 3rd callback to `onEnter` hooks. You can do it later. That's only good for manual checks though, where you want to manually add the `onEnter` hooks.

If you are using `getComponents` for async routes, you need to do something more complex with `RoutingContext`. I haven't looked at the too deeply, so I don't understand it enough to explain, but the folks in #rackt on discord were more than helpful.

The idea though is that we can figure this out on the react-router side, and benefit from that community instead of re-inventing stuff. If you want something more redux-like (doing it through actions or something) you can use redux-router or build off of this library.

We may eventually include some basic support for things like data fetching if it's 1. really helpful,  2. is simple, and 3. doesn't constrain users who want to do it another way.

**Comment by Dattaya** [comment]
@IwanKaramazow, I mean adding this behavior programmatically-dynamically.
@jlongster thank you again, your answers are very helpful. I don't have any more questions, but leave the decision of whether to close this issue or not to you.

**Comment by Dattaya** [comment]
> doesn't constrain users who want to do it another way.

It probably will, it can be described as a pattern/best practice/recipe in `react-router` docs.

**Comment by jlongster** [comment]
I will add examples soon. Closing this for now.
