### ISSUE TITLE
<base href="..."> ignored

### ISSUE THREAD

**Issue by PixnBits** [jlongster/redux-simple-router#62]
It appears that [the initial state looks at only the current location](https://github.com/jlongster/redux-simple-router/blob/c72dd571884a18b64a05262a36843852d74eb608/src/index.js#L22) without regard to a `<base>` tag being present (value available in [`document.baseURI`](https://developer.mozilla.org/en-US/docs/Web/API/Node/baseURI)).

Is this correct? Is this a use case (webapp at a level other than domain-level) desired to be solved by this package?

**Comment by kjbekkelund** [comment]
I've never used the `<base>` tag, so not sure what we need to think about there, but could you test your code with master? Quite a few changes to how we handle the location, might be it helps.

If you're using npm, you can test master with:

```
"redux-simple-router": "https://github.com/jlongster/redux-simple-router.git#master"
```

**Comment by jlongster** [comment]
I think it's bad that we look directly at `window.location`, because we're supposed to just be looking at the `history` object. The problem is the API is a little awkward right now: there is no `getCurrentLocation` for various reasons, but the `listen` function is called immediately the first time it registers with the initial location.

I've mentioned this in another thread (don't have the link) but we should probably just reset the initial state with the first location we're given. Then we're just inheriting whatever behavior `history` has. Whether or not it supports `base` is an issue that can be talked about there.

**Comment by ellbee** [comment]
I think this may be it: https://github.com/jlongster/redux-simple-router/pull/38#issuecomment-159656061

**Comment by kjbekkelund** [comment]
@jlongster Master no longer relies on `window.location`, only on the `location` received from `history.listen`. Might help, but never needed `<base>`, so not sure.

**Comment by PixnBits** [comment]
Fantastic, looks to be working! I'll be looking forward to the next release :+1:
